import { generateStrategicJSON, providerStatus } from '../ai/provider.js'
import { buildStrategyPrompt } from './prompt.js'
import { runDeterministicStrategy } from './deterministicEngine.js'
import { normalizeStrategy } from './schema.js'

/**
 * LangGraph-compatible orchestration layer.
 *
 * This is a genuine node/state graph — each node reads and writes a single
 * shared `state` object and runs in a fixed sequence, exactly like a
 * LangGraph StateGraph would. It intentionally mirrors LangGraph's
 * node/state/edge model (rather than depending on the `langgraph` Python
 * package) so the workflow stays inside the existing, stable Node/Express
 * backend instead of introducing a second runtime for a student demo.
 * Swapping this file's body for an actual LangGraph StateGraph.invoke() call
 * would not change any caller in server/index.js or the React app — the
 * node boundaries and shared state are already structured that way.
 *
 * Fields the AI is allowed to influence are merged in from the AI provider;
 * everything numeric/structural (mitigations, improvements, quick wins,
 * critical risks) always comes from the deterministic engines below, so a
 * bad or missing AI response can never corrupt the risk-derived data.
 */

const AI_OWNED_FIELDS = [
  'strategicVerdict', 'confidence', 'priority', 'executiveStrategy',
  'keyInsights', 'investorPerspective', 'marketStrategy', 'executionStrategy',
  'reasoning', 'explainability', 'nextBestAction', 'topPriorities'
]

function makeNode(agent, description, fn) {
  return { agent, description, fn }
}

export async function runStrategyGraph(input) {
  const state = { ...input, workflow: [] }

  const nodes = [
    makeNode('Market Agent', 'Reading market signals (TAM/SAM/SOM, competitor share)', (s) => {
      s.marketSummary = `${s.market.sectorName}: TAM ₹${Math.round(s.market.tam)} Cr, SOM ₹${Math.round(s.market.som)} Cr, top competitor ${s.market.topShare}% share.`
    }),
    makeNode('Risk Agent', 'Evaluating computed risk categories', (s) => {
      s.riskSummary = `${s.risk.overallLevel} overall risk (${s.risk.overallScore}/100), ${s.risk.criticalFlags} critical categor${s.risk.criticalFlags === 1 ? 'y' : 'ies'}.`
    }),
    makeNode('SWOT Agent', 'Synthesizing strengths, weaknesses, opportunities, threats', (s) => {
      s.swot = deriveSWOT(s.market, s.risk)
    }),
    makeNode('Feasibility Agent', 'Scoring launch readiness dimensions', (s) => {
      s.feasibilitySummary = `${s.readiness.overall}% overall readiness; weakest dimension: ${[...s.readiness.breakdown].sort((a, b) => a.value - b.value)[0].label}.`
    }),
    makeNode('Strategy Agent', 'Generating strategic reasoning', async (s) => {
      const draft = runDeterministicStrategy(s)
      s.deterministicDraft = draft

      const status = providerStatus()
      s.aiStatus = status

      if (!status.configured) {
        s.aiResult = null
        return
      }

      const prompt = buildStrategyPrompt({ ...s, draft })
      const aiResponse = await generateStrategicJSON(prompt)
      s.aiResponseMeta = aiResponse
      s.aiResult = aiResponse.ok ? aiResponse.data : null
    }),
    makeNode('Mitigation Agent', 'Building mitigation plan from risk categories', (s) => {
      // Already computed inside the deterministic draft — this node's job is
      // to confirm it against shared state, exactly as a LangGraph node would
      // read the accumulated state rather than recomputing from scratch.
      s.mitigations = s.deterministicDraft.mitigations
    }),
    makeNode('Recommendation Agent', 'Assembling top priorities and quick wins', (s) => {
      s.finalStrategy = mergeStrategy(s.deterministicDraft, s.aiResult)
    })
  ]

  for (const node of nodes) {
    const entry = { agent: node.agent, description: node.description, status: 'running' }
    state.workflow.push(entry)
    const startedAt = Date.now()
    try {
      await node.fn(state)
      entry.status = 'complete'
      entry.durationMs = Date.now() - startedAt
    } catch (err) {
      entry.status = 'error'
      entry.error = err.message || String(err)
      entry.durationMs = Date.now() - startedAt
      // Non-fatal — later nodes can still fall back to deterministic data.
    }
  }

  const strategy = normalizeStrategy(state.finalStrategy || state.deterministicDraft)

  return {
    strategy,
    workflow: state.workflow,
    meta: {
      provider: state.aiResponseMeta?.ok ? state.aiStatus.provider : 'fallback',
      model: state.aiResponseMeta?.ok ? state.aiResponseMeta.model : null,
      aiAttempted: !!state.aiStatus?.configured,
      aiError: state.aiResponseMeta && !state.aiResponseMeta.ok ? state.aiResponseMeta.error : null,
      statusLabel: state.aiResponseMeta?.ok
        ? `Strategic reasoning generated by ${state.aiStatus.provider} (${state.aiResponseMeta.model})`
        : 'Strategic reasoning generated from platform intelligence',
      generatedAt: new Date().toISOString()
    }
  }
}

function mergeStrategy(draft, aiResult) {
  if (!aiResult) return draft
  const merged = { ...draft }
  for (const field of AI_OWNED_FIELDS) {
    if (aiResult[field] !== undefined && aiResult[field] !== null) {
      merged[field] = aiResult[field]
    }
  }
  return merged
}

function deriveSWOT(market, risk) {
  const strengths = []
  const weaknesses = []
  const opportunities = []
  const threats = []

  if (risk.marketFit >= 65) strengths.push('Strong SOM/TAM alignment indicates real market fit.')
  if (market.topShare < 20) opportunities.push('Fragmented competitive landscape leaves room for a focused entrant.')
  else threats.push(`${market.competitors[0]?.name || 'Category leader'} concentration raises the bar for differentiation.`)

  risk.categories.forEach((c) => {
    if (c.level === 'HIGH') weaknesses.push(c.label)
    if (c.level === 'LOW') strengths.push(`${c.label} is well controlled.`)
  })

  if (market.tamGrowth > market.samGrowth) opportunities.push('TAM is expanding faster than SAM — room to grow serviceable share over time.')

  return { strengths, weaknesses, opportunities, threats }
}
